spring:
  application:
    name: chatroom
  datasource:
    #1.JDBC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chatroom?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 111111
    druid:
      #2.连接池配置
      #初始化连接池的连接数量 大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 5000
      #3.基础监控配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        #设置不统计哪些URL
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
        session-stat-max-count: 100
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        #设置监控页面的登录名和密码
        login-username: admin
        login-password: admin
        allow: 127.0.0.1
        #deny: 192.168.1.100
  #邮件配置
  mail:
    host: mail.vvli.club
    username: ljh/ljh
    password: C47NTIhnqrnvkWvm01mgMJ7W
    properties:
      from: postmaster@sdyun.store
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

server:
  port: 9090

logging:
  level:
    org:
      springboot:
        chatroom:
          dao: debug

rsa:
  key:
    private: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC++4IDxh/4Owlq
      gH1eNbtHtUBTCYyfi3DJJj9D/QaKVb7RyM6AU9BhFHWUU0L8ZMmMSsJw0QIOzbY2
      Hwl758u6YAh+c354/WfxjAXou8iNrnDLwn7xrAFqOkLTPuFYMn/eitjLuZVO3mSi
      iqAJ5LlNwIIPLOJK67dD5ECfClici0tdtgNEt8tIb9N4dS3HbUVnu3ImESsgDqXp
      +kwMJpH/3IJZDLlE4xVEY2BMyn8fwbX3NbvWhU1+5NAEF9QKzx8+8fdme9Su2YF+
      qvdhrmhpMVUmcDQqi33XBgb/w1gR0u+kIOaFr2sdubhdQz3v8epj0dRetwS7bth5
      /ZLnF9w9AgMBAAECggEBAL6WDMwpVlQIzj+7E+EFK+zGgveayvuYUqhZg78cbP91
      zCRcCT9k5MlMen3XjTyEc+GN5XZiDXSqcxCVboh47AUEutU9+lNRRv50ppz3cI97
      KlMcuEQCS7Mviup2kLjMRHDYDLtZaxe2taTDRCw7VXSzDNeKChWMH2ogCSDtWTp1
      yh4Qp5wymcbaFHMmINt9elh2rBsD8JD5W6d/sL30l08f02VVhTc0GoUyZkIJ1Hyq
      L8KdurWvpZLWiy85IFYQ+HVddJKlNNInXey56kqFtK5pq4ckSlivLPEW/4jMvpCG
      mNdRNSa3+PFJMStWjgr07PbNErr6jhTUrl9dHPU9u6ECgYEA3vEZFFh48KQTf9YZ
      fqDezDQYy7qNykbRNHC/QPwm9TnURlu6FnNyTv1lfHRMqNyShFyhYbIXzGAuS8jf
      81ettR9jQ5zIvTNgXS5ulKc1YCxTn5Gs9YC44WKCxWA/o1WnpZVRtG28uXtXVOlB
      k8iU1mWk88KeP6X54iv5AgpCfJUCgYEA2006nGXfyIhbtADy/O700VYr2DMTkk5o
      TnLnXLFmZLXAg6XzpSz1t6j7pTUFi00ox8v66ebSqTRd0W8p9c0QyNQqB8Lht5qN
      V+NXHs83+boYZZbEe9QaYq3Hg/63ocDjneUbJ66H+rKn1Z6uceMuJ1Ok6WCrJTbD
      w6hDq9GxzwkCgYEAis1rAurOaWyOI2JGPzujW1n4Mid1DgInUFH+EVSsYLNfgWqs
      ojvAaIOFgwXZkKy7oCMX6v55qKodSNvI6vWk1gazw63CoWFyVrGI8Y5lQfp3GfsV
      x0gcU18E8iQpmuTCWuprkz1badPsHJaZWIxidlWUbJu38QLCYFlmUCnZGT0CgYAN
      Y2SdobaMxo5aqegruublVM5ub4fVWcYSa/9l8EqhAVuUbfA2+Eyz/rQGPPtuqrI/
      qFtUJkxcGh9UJuY35GIO8Kz0NliTXfMdF3r9HYd8Tnko0pCCQsutlJBmpYlObbk3
      rYH/5S7WBkwqxXo+57Cso/Wgbc9lATfoXQBsn+usCQKBgGqmVUBYBjzbmdgHyTwH
      +By1OlHs4EWPSuyccWA4HCGHM+ZLr5gK87Ne01Jjeqm2XrGuor+2eYaXCGNc2So4
      /DenLLCJy3JNsjr+0ze6xrOXthscVnhM9xwIhKnwJVRj9kgkXFF69b/x0j8QG4l7
      ruOCqcxN/Gk9V+ITtYyDFsTr
    public: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvvuCA8Yf+DsJaoB9XjW7
      R7VAUwmMn4twySY/Q/0GilW+0cjOgFPQYRR1lFNC/GTJjErCcNECDs22Nh8Je+fL
      umAIfnN+eP1n8YwF6LvIja5wy8J+8awBajpC0z7hWDJ/3orYy7mVTt5kooqgCeS5
      TcCCDyziSuu3Q+RAnwpYnItLXbYDRLfLSG/TeHUtx21FZ7tyJhErIA6l6fpMDCaR
      /9yCWQy5ROMVRGNgTMp/H8G19zW71oVNfuTQBBfUCs8fPvH3ZnvUrtmBfqr3Ya5o
      aTFVJnA0Kot91wYG/8NYEdLvpCDmha9rHbm4XUM97/HqY9HUXrcEu27Yef2S5xfc
      PQIDAQAB
